modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/mbg206/pmw-renderer/issues"

[[mods]]
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforge.net/docs/misc/updatechecker/
#updateJSONURL="https://raw.githubusercontent.com/mbg206/pmw-renderer/refs/heads/main/update.json"
displayURL="https://modrinth.com/mod/pmw-renderer"
logoFile= "logo.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "CLIENT"
[[dependencies."${mod_id}"]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version}]"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies."${mod_id}"]]
    modId="pmweather"
    type="required"
    versionRange="[0.16.4]"
    ordering="AFTER"
    side="CLIENT"
